### ISSUE TITLE
[ticketshop] Gebruik een website URL om een sponsorbalk op te nemen

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomladagen.nl#102]
Gebruik een URL naar een afbeelding op de server waar de sponsoren in worden genoemd, we hoeven dan alleen die afbeelding te updaten om nieuwe sponsoren te tonen.

**Comment by crommie** [comment]
Hoe moet dat?  Want er moet er binnenkort weer eentje online. Anja (vanaf de mobiel)Op 19 december 2017 om 21:19 schreef RolandD <notifications@github.com>:  Gebruik een URL naar een afbeelding op de server waar de sponsoren in worden genoemd, we hoeven dan alleen die afbeelding te updaten om nieuwe sponsoren te tonen.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by roland-d** [comment]
@crommie Het idee is om de sponsoren in een afbeelding te hebben. Die afbeelding wordt opgenomen in de orderbevestiging. We kunnen deze ook opnemen in de nieuwsbrief. Als we dan die afbeelding bijwerken ziet men meteen de nieuwste versie. Dan hoeven we geen losse sponsor logo's te gaan plakken in die orderbevestiging. Dat is het idee.

**Comment by crommie** [comment]
Sponsors worden sinds dit jaar niet meer op de tickets gezet. Zie pakketten. Groeten! Op 20 december 2017 om 8:37 schreef RolandD <notifications@github.com>:  @crommie Het idee is om de sponsoren in een afbeelding te hebben. Die afbeelding wordt opgenomen in de orderbevestiging. We kunnen deze ook opnemen in de nieuwsbrief. Als we dan die afbeelding bijwerken ziet men meteen de nieuwste versie. Dan hoeven we geen losse sponsor logo's te gaan plakken in die orderbevestiging. Dat is het idee.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by roland-d** [comment]
Duidelijk. Dank je.
